In [1]:
%matplotlib inline

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## 分析107年結婚對數按男女雙方年齡分

In [2]:
df = pd.read_csv('https://quality.data.gov.tw/dq_download_csv.php?nid=102822&md5_url=ba570b3564663eebbc9480a3c282213c')

C:\Users\ASUS\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3057: DtypeWarning: Columns (0,5) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [4]:
df.head()

  statistic_yyy according site_id female_age male_age marry_pair
0          統計年度       按照別     區域別       女方年齡     男方年齡       結婚對數
1           107    按發生日期分  新北市板橋區      未滿15歲    未滿15歲          0
2           107    按發生日期分  新北市板橋區      未滿15歲      15歲          0
3           107    按發生日期分  新北市板橋區      未滿15歲      16歲          0
4           107    按發生日期分  新北市板橋區      未滿15歲      17歲          0

### 刪去不必要的欄位

In [9]:
df.drop("according",axis=1,inplace=True)

In [10]:
df.head()

  statistic_yyy site_id female_age male_age marry_pair
0          統計年度     區域別       女方年齡     男方年齡       結婚對數
1           107  新北市板橋區      未滿15歲    未滿15歲          0
2           107  新北市板橋區      未滿15歲      15歲          0
3           107  新北市板橋區      未滿15歲      16歲          0
4           107  新北市板橋區      未滿15歲      17歲          0

## 找出男方、女方年齡１８歲　結婚對數為１

In [28]:
df[(df.female_age=='18歲')&(df.male_age=='18歲')&(df.marry_pair == '1')]

       statistic_yyy site_id female_age male_age marry_pair
2813             107  新北市新莊區        18歲      18歲          1
4841             107  新北市鶯歌區        18歲      18歲          1
5517             107  新北市三峽區        18歲      18歲          1
9573             107  新北市五股區        18歲      18歲          1
20389            107  臺北市信義區        18歲      18歲          1
32557            107  桃園市八德區        18歲      18歲          1
33909            107  桃園市平鎮區        18歲      18歲          1
34585            107  桃園市新屋區        18歲      18歲          1
39317            107  臺中市北　區        18歲      18歲          1
48105            107  臺中市大雅區        18歲      18歲          1
67709            107  臺南市新化區        18歲      18歲          1
77173            107  臺南市東　區        18歲      18歲          1
82581            107  高雄市左營區        18歲      18歲          1
87313            107  高雄市前鎮區        18歲      18歲          1
88665            107  高雄市小港區        18歲      18歲          1
89341            107  高雄市鳳山一        18歲      18歲          1
90693            107  高雄市林園區        18歲      18歲          1
92045            107  高雄市大樹區        18歲      18歲          1
93397            107  高雄市仁武區        18歲      18歲          1
98129            107  高雄市路竹區        18歲      18歲          1
103537           107  高雄市六龜區        18歲      18歲          1
117733           107  新竹縣新埔鎮        18歲      18歲          1
118409           107  新竹縣竹東鎮        18歲      18歲          1
119085           107  新竹縣湖口鄉        18歲      18歲          1
120437           107  新竹縣新豐鄉        18歲      18歲          1
124493           107  新竹縣五峰鄉        18歲      18歲          1
125845           107  苗栗縣頭份市        18歲      18歲          1
127873           107  苗栗縣竹南鎮        18歲      18歲          1

## 輸入分別想查詢的數據

In [33]:
df[(df.female_age== input("輸入女方歲數"))&(df.male_age==input("輸入男方歲數"))]

輸入女方歲數18歲
輸入男方歲數30歲

       statistic_yyy site_id female_age male_age marry_pair
121              107  新北市板橋區        18歲      30歲          0
797              107  新北市三重區        18歲      30歲          1
1473             107  新北市中和區        18歲      30歲          0
2149             107  新北市永和區        18歲      30歲          0
2825             107  新北市新莊區        18歲      30歲          0
3501             107  新北市新店區        18歲      30歲          1
4177             107  新北市樹林區        18歲      30歲          0
4853             107  新北市鶯歌區        18歲      30歲          0
5529             107  新北市三峽區        18歲      30歲          0
6205             107  新北市淡水區        18歲      30歲          1
6881             107  新北市汐止區        18歲      30歲          0
7557             107  新北市瑞芳區        18歲      30歲          0
8233             107  新北市土城區        18歲      30歲          0
8909             107  新北市蘆洲區        18歲      30歲          1
9585             107  新北市五股區        18歲      30歲          0
10261            107  新北市泰山區        18歲      30歲          0
10937            107  新北市林口區        18歲      30歲          0
11613            107  新北市深坑區        18歲      30歲          0
12289            107  新北市石碇區        18歲      30歲          0
12965            107  新北市坪林區        18歲      30歲          0
13641            107  新北市三芝區        18歲      30歲          0
14317            107  新北市石門區        18歲      30歲          0
14993            107  新北市八里區        18歲      30歲          0
15669            107  新北市平溪區        18歲      30歲          0
16345            107  新北市雙溪區        18歲      30歲          0
17021            107  新北市貢寮區        18歲      30歲          0
17697            107  新北市金山區        18歲      30歲          0
18373            107  新北市萬里區        18歲      30歲          0
19049            107  新北市烏來區        18歲      30歲          0
19725            107  臺北市松山區        18歲      30歲          0
...              ...     ...        ...      ...        ...
229961           107  花蓮縣萬榮鄉        18歲      30歲          0
230637           107  花蓮縣卓溪鄉        18歲      30歲          0
231313           107  澎湖縣馬公市        18歲      30歲          0
231989           107  澎湖縣湖西鄉        18歲      30歲          0
232665           107  澎湖縣白沙鄉        18歲      30歲          0
233341           107  澎湖縣西嶼鄉        18歲      30歲          0
234017           107  澎湖縣望安鄉        18歲      30歲          0
234693           107  澎湖縣七美鄉        18歲      30歲          0
235369           107  基隆市中正區        18歲      30歲          0
236045           107  基隆市七堵區        18歲      30歲          0
236721           107  基隆市暖暖區        18歲      30歲          0
237397           107  基隆市仁愛區        18歲      30歲          0
238073           107  基隆市中山區        18歲      30歲          0
238749           107  基隆市安樂區        18歲      30歲          0
239425           107  基隆市信義區        18歲      30歲          0
240101           107  新竹市東　區        18歲      30歲          0
240777           107  新竹市北　區        18歲      30歲          0
241453           107  新竹市香山區        18歲      30歲          0
242129           107  嘉義市東　區        18歲      30歲          0
242805           107  嘉義市西　區        18歲      30歲          0
243481           107  金門縣金城鎮        18歲      30歲          0
244157           107  金門縣金湖鎮        18歲      30歲          0
244833           107  金門縣金沙鎮        18歲      30歲          0
245509           107  金門縣金寧鄉        18歲      30歲          0
246185           107  金門縣烈嶼鄉        18歲      30歲          0
246861           107  金門縣烏坵鄉        18歲      30歲          0
247537           107  連江縣南竿鄉        18歲      30歲          0
248213           107  連江縣北竿鄉        18歲      30歲          0
248889           107  連江縣莒光鄉        18歲      30歲          0
249565           107  連江縣東引鄉        18歲      30歲          0

[370 rows x 5 columns]